services:
  %%__SERVICE_NAME__%%:
    environment:
      - COLORTERM
      - ITERM_PROFILE
      - ITERM_SESSION_ID
      - LC_TERMINAL
      - LC_TERMINAL_VERSION
      - TERM
      - TERM_PROGRAM
      - TERM_PROGRAM_VERSION
      - TERM_SESSION_ID
    image:
      %%__IMAGE_NAME__%%
    # Uncomment to build from custom dockerfile, then add "-custom" to the above image name.
    #build:
    #  context: .
    #  dockerfile: Dockerfile.nvim.local  # make sure
    stdin_open: true
    tty: true
    entrypoint: nvim
    volumes:
      - .:/src:consistent
      - ~/.dotfiles/.config/nvim:/root/.config/nvim:ro
      - ~/.dotfiles/.config/copilot:/root/.config/copilot:ro
      - nvim-data:/root/.local/share/nvim
volumes:
  nvim-data:
    external: true
